_wandb:
    value:
        cli_version: 0.21.1
        e:
            ealfr08b14s8q87kmpq4mywk5j96b35a:
                codePath: ppo/train.py
                codePathLocal: train.py
                cpu_count: 24
                cpu_count_logical: 24
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1065418129408"
                        used: "499263606784"
                email: lilin22wz@gmail.com
                executable: /home/v-zhaowan/miniconda3/envs/rag_ppo/bin/python
                git:
                    commit: fe747217b21e79080736b2efe30f183a1e561108
                    remote: https://github.com/lilinwz/dpo-rag.git
                gpu: NVIDIA A100 80GB PCIe
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-7dc5a7c4-fc5a-688e-fac3-6ef2c3587d64
                host: GCRAZGDL1627
                memory:
                    total: "232209727488"
                os: Linux-6.8.0-1031-azure-x86_64-with-glibc2.35
                program: /home/v-zhaowan/zhaowang/rag/ppo/train.py
                python: CPython 3.10.18
                root: /home/v-zhaowan/zhaowang/rag/ppo
                startedAt: "2025-08-26T07:30:56.928991Z"
                writerId: ealfr08b14s8q87kmpq4mywk5j96b35a
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 75
                - 84
                - 98
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 71
                - 75
                - 84
                - 98
            "3":
                - 13
                - 16
            "4": 3.10.18
            "5": 0.21.1
            "6": 4.55.4
            "12": 0.21.1
            "13": linux-x86_64
batch_size:
    value: 4
horizon:
    value: 10000
init_kl_coef:
    value: 0.1
learning_rate:
    value: 1.41e-05
max_interaction_steps:
    value: 7
mini_batch_size:
    value: 1
ppo_epochs:
    value: 4
target:
    value: 6
trl_ppo_trainer_config:
    value:
        adap_kl_ctrl: true
        backward_batch_size: 1
        batch_size: 4
        cliprange: 0.2
        cliprange_value: 0.2
        compare_steps: 1
        dataset_num_proc: null
        early_stopping: false
        exp_name: train
        forward_batch_size: null
        gamma: 1
        global_backward_batch_size: 1
        global_batch_size: 4
        gradient_accumulation_steps: 1
        gradient_checkpointing: false
        horizon: 10000
        init_kl_coef: 0.1
        is_encoder_decoder: false
        is_peft_model: true
        kl_penalty: kl
        lam: 0.95
        learning_rate: 1.41e-05
        log_with: wandb
        max_grad_norm: null
        mini_batch_size: 1
        model_name: gpt2
        optimize_cuda_cache: null
        optimize_device_cache: false
        ppo_epochs: 4
        query_dataset: stanfordnlp/imdb
        ratio_threshold: 10
        remove_unused_columns: false
        reward_model: sentiment-analysis:lvwerra/distilbert-imdb
        score_clip: null
        seed: 0
        steps: 20000
        target: 6
        target_kl: 1
        task_name: null
        total_ppo_epochs: 5000
        tracker_kwargs/wandb/config/batch_size: 4
        tracker_kwargs/wandb/config/horizon: 10000
        tracker_kwargs/wandb/config/init_kl_coef: 0.1
        tracker_kwargs/wandb/config/learning_rate: 1.41e-05
        tracker_kwargs/wandb/config/max_interaction_steps: 7
        tracker_kwargs/wandb/config/mini_batch_size: 1
        tracker_kwargs/wandb/config/ppo_epochs: 4
        tracker_kwargs/wandb/config/target: 6
        tracker_kwargs/wandb/name: ppo-test
        tracker_project_name: trl
        use_score_norm: false
        use_score_scaling: false
        vf_coef: 0.1
        whiten_rewards: false
        world_size: 1
