import json
import os
import hashlib
import re
import concurrent.futures
from tqdm import tqdm
from azure.identity import (
    AzureCliCredential,
    ChainedTokenCredential,
    ManagedIdentityCredential,
    get_bearer_token_provider
)
from openai import AzureOpenAI

# ================= 配置部分 =================
INPUT_FILE = "/home/v-zhaowan/ds/zhaowang/rag/data/raw/tree_new.jsonl"
OUTPUT_FILE = "/home/v-zhaowan/ds/zhaowang/rag/data/train_prm.jsonl"
MAX_WORKERS = 50 

# ================= PROMPT =================
SELECTOR_SYSTEM_PROMPT = """
You are an expert AI Tutor creating a training dataset for a reasoning model.
Your task is to review the "History" and a list of "Candidate Next Steps" (generated by MCTS), and select exactly ONE pair of (Positive, Negative) actions.

### SELECTION RULES:
1. **Positive Action**: The most logical, efficient step that moves towards the answer.
2. **Negative Action**: A step that is clearly worse (e.g., hallucination, logic error, or **redundant** search for info already in history).
3. **Semantic Deduplication (CRITICAL)**: 
   - The Negative action MUST be semantically different from the Positive action.
   - Do NOT select a negative sample if it is just a rephrasing of the positive one (e.g. "In what year..." vs "In which year...").
4. **NO FORCED SELECTION**:
   - If all candidates are good, OR all are bad, OR the negatives are just duplicates of the positive:
   - **RETURN NULL** (set has_valid_pair to false). Do NOT force a selection.

### OUTPUT FORMAT (JSON):
{
    "has_valid_pair": true/false,
    "positive_id": <id of the best candidate>,
    "negative_id": <id of the bad candidate>,
    "reason": "<brief explanation>"
}
"""

# ================= UTILS =================
def get_azure_client():
    scope = "api://trapi/.default"
    credential = get_bearer_token_provider(
        ChainedTokenCredential(AzureCliCredential(), ManagedIdentityCredential()), 
        scope
    )
    client = AzureOpenAI(
        azure_endpoint="https://trapi.research.microsoft.com/gcr/shared",
        azure_ad_token_provider=credential,
        api_version="2024-10-21",
        max_retries=3
    )
    return client

def normalize_mcts_q(q, n):
    if n <= 0:
        return 0.0
    return q / n

def format_check(action):
    tags = re.findall(r"</?[a-zA-Z]+>", action)

    if tags == ["<step>", "</step>", "<subquery>", "</subquery>", "<retrieval>", "</retrieval>"]:
        return True
    if tags == ["<step>", "</step>", "<subanswer>", "</subanswer>"]:
        return True
    if tags == ["<step>", "</step>", "<answer>", "</answer>"]:
        return True

    return False

def process_candidate_group(client, job_data):
    question = job_data['question']
    history = job_data['history']
    candidates = job_data['candidates'] 

    candidates_display = ""
    for cand in candidates:
        candidates_display += f"ID: {cand['id']}\nAction: {cand['action']}\n[MCTS]: Q={cand['q']:.2f}, N={cand['n']}\n\n"

    user_content = f"""
    ### Question:
    {question}

    ### History:
    {history}

    ### Candidates:
    {candidates_display}
    """

    try:
        response = client.chat.completions.create(
            model="gpt-4o_2024-11-20",
            messages=[
                {"role": "system", "content": SELECTOR_SYSTEM_PROMPT},
                {"role": "user", "content": user_content}
            ],
            temperature=0.7,
            response_format={"type": "json_object"}
        )
        
        result_json = json.loads(response.choices[0].message.content.strip())

        if result_json.get("has_valid_pair") is True:
            pos_id = result_json.get('positive_id')
            neg_id = result_json.get('negative_id')
            
            pos_cand = next((c for c in candidates if c['id'] == pos_id), None)
            neg_cand = next((c for c in candidates if c['id'] == neg_id), None)
            
            if pos_cand and neg_cand:
                return {
                    "type": "gpt_selection",
                    "input": {
                        "question": question,
                        "history": history
                    },
                    "chosen": {
                        "new_step": pos_cand['action'],
                        "mcts_stats": {"q": pos_cand['q'], "n": pos_cand['n']}
                    },
                    "rejected": {
                        "new_step": neg_cand['action'],
                        "mcts_stats": {"q": neg_cand['q'], "n": neg_cand['n']}
                    },
                    "label": {
                        "gpt_reason": result_json.get("reason"),
                        "chosen_reward": 1.0,
                        "rejected_reward": 0.0 
                    }
                }
    except Exception as e:
        pass
    
    return None

def traverse_and_collect_jobs(node, question, history):
    jobs = []
    children = node.get('children', [])
    if not children:
        return []

    visited_children = [c for c in children if c.get('n', 0) >= 1 and format_check(c.get('action', ""))]
    if len(visited_children) >= 2:
        candidates = []
        for idx, child in enumerate(visited_children):
            action_text = child.get('action')
            candidates.append({
                "id": idx,
                "action": action_text,
                "q": normalize_mcts_q(child.get('q', 0), child.get('n', 0)),
                "n": child.get('n', 0)
            })
        
        if candidates:
            jobs.append({
                "question": question,
                "history": history,
                "candidates": candidates
            })

    for child in visited_children:
        if child.get('n', 0) >= 3:
            action_text = child.get('action')
            new_history = history + action_text
            subjobs = traverse_and_collect_jobs(child, question, new_history)
            jobs.extend(subjobs)
    return jobs

def load_processed_set(filepath):
    processed = set()
    if os.path.exists(filepath):
        print(f"Loading existing processed data from {filepath}...")
        with open(filepath, 'r', encoding='utf-8') as f:
            for line in f:
                try:
                    obj = json.loads(line)
                    if "input" in obj:
                        q = obj["input"].get("question", "")
                        processed.add(q)
                except Exception:
                    continue
    print(f"Found {len(processed)} processed items.")
    return processed

def main():
    global_client = get_azure_client()
    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)

    processed_set = load_processed_set(OUTPUT_FILE)

    jobs_to_process = []
    print(f"Parsing Trees from {INPUT_FILE}...")
    with open(INPUT_FILE, 'r', encoding='utf-8') as f:
        for line in tqdm(f, desc="Parsing"):
            line = line.strip()
            if not line: continue
            try:
                tree_obj = json.loads(line)
                idx = tree_obj.get('id')
                q_text = tree_obj.get('question', '')
                root = tree_obj.get('mcts_tree', {})
                
                extracted_jobs = traverse_and_collect_jobs(root, q_text, "")
                for job in extracted_jobs:
                    if job['question'] not in processed_set:
                        jobs_to_process.append(job)

            except json.JSONDecodeError:
                continue
    
    print(f"Collected {len(jobs_to_process)} groups of candidates for GPT selection.")
    
    if not jobs_to_process:
        print("No new jobs to process.")
        return

    print("Starting GPT-4o Selection...")
    valid_count = 0
    with open(OUTPUT_FILE, 'a', encoding='utf-8') as f_out:
        with concurrent.futures.ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
            futures = [executor.submit(process_candidate_group, global_client, item) for item in jobs_to_process]
            
            for future in tqdm(concurrent.futures.as_completed(futures), total=len(jobs_to_process)):
                try:
                    res = future.result()
                    if res:
                        f_out.write(json.dumps(res, ensure_ascii=False) + "\n")
                        f_out.flush()
                        valid_count += 1
                except Exception:
                    pass
    
    print(f"Done. Generated {valid_count} valid pairwise samples.")

if __name__ == "__main__":
    main()