import json
import os
import re
import concurrent.futures
from tqdm import tqdm
import numpy as np
import torch
from sentence_transformers import SentenceTransformer
from typing import List, Dict, Any

from azure.identity import (
    AzureCliCredential,
    ChainedTokenCredential,
    ManagedIdentityCredential,
    get_bearer_token_provider
)
from openai import AzureOpenAI

# ================= 配置部分 =================
# 输入：Script B 生成的 Tree 文件
INPUT_FILE = "/home/v-zhaowan/ds/zhaowang/rag/data/raw/tree_mulsique.jsonl"
# 输出：GPT 挑选后的 PVM 训练数据
OUTPUT_FILE = "/home/v-zhaowan/ds/zhaowang/rag/data/raw/mulsique_pvm.jsonl"
# 原始数据：用于加载 E5 检索所需的 paragraph 内容
ORIGINAL_DATA_PATH = "/home/v-zhaowan/ds/zhaowang/rag/data/MulSiQue/musique_ans_v1.0_train.jsonl" 
E5_MODEL_NAME = 'intfloat/e5-large-v2'

MAX_WORKERS = 10 

# ================= PROMPT =================
SELECTOR_SYSTEM_PROMPT = """
You are an expert AI Tutor creating a training dataset for a reasoning model.
Your task is to review the "History" and a list of "Candidate Next Steps" (generated by MCTS), and select exactly ONE pair of (Positive, Negative) actions.

### SELECTION RULES:
1. **Positive Action**: The most logical, efficient step that moves towards the answer.
2. **Negative Action**: A step that is clearly worse (e.g., hallucination, logic error, or **redundant** search for info already in history).
3. **Semantic Deduplication (CRITICAL)**: 
   - The Negative action MUST be semantically different from the Positive action.
   - Do NOT select a negative sample if it is just a rephrasing of the positive one (e.g. "In what year..." vs "In which year...").
4. **NO FORCED SELECTION**:
   - If all candidates are good, OR all are bad, OR the negatives are just duplicates of the positive:
   - **RETURN NULL** (set has_valid_pair to false). Do NOT force a selection.

### OUTPUT FORMAT (JSON):
{
    "has_valid_pair": true/false,
    "positive_id": <id of the best candidate>,
    "negative_id": <id of the bad candidate>,
    "reason": "<brief explanation>"
}
"""

# ================= UTILS =================

def get_azure_client():
    scope = "api://trapi/.default"
    credential = get_bearer_token_provider(
        ChainedTokenCredential(AzureCliCredential(), ManagedIdentityCredential()), 
        scope
    )
    client = AzureOpenAI(
        azure_endpoint="https://trapi.research.microsoft.com/gcr/shared",
        azure_ad_token_provider=credential,
        api_version="2024-10-21",
        max_retries=3
    )
    return client

class E5VectorRetriever:
    """
    适配 MuSiQue 数据格式的检索器
    paragraphs 结构: [{"title": "t1", "paragraph_text": "p1"}, ...]
    """
    def __init__(self, paragraphs: List[Dict[str, Any]], model: SentenceTransformer):
        self.model = model
        
        # 适配 MuSiQue 字段名
        self.titles = [item.get("title", "") for item in paragraphs]
        self.passages = [item.get("paragraph_text", "") for item in paragraphs]
        
        self.corpus = [f"Title: {t}\n{p}" for t, p in zip(self.titles, self.passages)]

        if not self.corpus:
            self.corpus_embeddings = None
            return

        emb = self.model.encode(self.corpus, convert_to_tensor=False, show_progress_bar=False)
        emb = np.asarray(emb)
        self.corpus_embeddings = emb.astype(np.float32)
        self.corpus_embeddings /= np.linalg.norm(self.corpus_embeddings, axis=1, keepdims=True) + 1e-12

    def retrieve(self, query: str, top_k: int = 3) -> str:
        if self.corpus_embeddings is None or not query:
            return ""
        
        q_emb = self.model.encode(f"query: {query}", convert_to_tensor=False, show_progress_bar=False)
        q_emb = np.asarray(q_emb)
        q_emb = q_emb.astype(np.float32)
        q_emb /= np.linalg.norm(q_emb) + 1e-12

        scores = np.dot(self.corpus_embeddings, q_emb)
        k = min(top_k, len(scores))
        idxs = np.argsort(-scores)[:k]
        
        retrieved_list = [f"Title: {self.titles[idx]}\n{self.passages[idx]}" for idx in idxs]
        return "\n".join(retrieved_list)

def perform_retrieval_string(action_text, retriever):
    """
    提取 subquery 并执行检索，返回拼接好的 XML 字符串
    """
    if not action_text: return ""
    subquery_match = re.search(r"<subquery>\n(.*?)</subquery>", action_text, re.DOTALL)
    if subquery_match:
        subquery = subquery_match.group(1).strip()
        if retriever:
            docs_text = retriever.retrieve(subquery, top_k=3)
            if docs_text:
                return f"\n{docs_text}\n</retrieval>\n"
            else:
                return "\n[No documents found]\n</retrieval>\n"
        else:
            return "\n[Warning: Context missing]\n</retrieval>\n"
    return ""

def normalize_mcts_q(q, n):
    if n == 0: return 0.0
    return max(0.0, min(1.0, q / n))

def process_candidate_group(client, job_data):
    question = job_data['question']
    history = job_data['history']
    candidates = job_data['candidates'] 

    # 格式化 Candidates 供 GPT 查看
    candidates_display = ""
    for cand in candidates:
        candidates_display += f"ID: {cand['id']}\nAction: {cand['action']}\n[MCTS]: Q={cand['q']:.2f}, N={cand['n']}\n\n"

    user_content = f"""
    ### Question:
    {question}

    ### History:
    {history}

    ### Candidates:
    {candidates_display}
    """

    try:
        response = client.chat.completions.create(
            model="gpt-4o_2024-11-20",
            messages=[
                {"role": "system", "content": SELECTOR_SYSTEM_PROMPT},
                {"role": "user", "content": user_content}
            ],
            temperature=0.7, # 稍微增加一点温度以增加多样性，或者保持 0.0 以求稳
            response_format={"type": "json_object"}
        )
        
        result_json = json.loads(response.choices[0].message.content.strip())

        if result_json.get("has_valid_pair") is True:
            pos_id = result_json.get('positive_id')
            neg_id = result_json.get('negative_id')
            
            pos_cand = next((c for c in candidates if c['id'] == pos_id), None)
            neg_cand = next((c for c in candidates if c['id'] == neg_id), None)
            
            if pos_cand and neg_cand:
                return {
                    "type": "gpt_selection",
                    "input": {
                        "question": question,
                        "history": history
                    },
                    "chosen": {
                        "new_step": pos_cand['action'],
                        "mcts_stats": {"q": pos_cand['q'], "n": pos_cand['n']}
                    },
                    "rejected": {
                        "new_step": neg_cand['action'],
                        "mcts_stats": {"q": neg_cand['q'], "n": neg_cand['n']}
                    },
                    "label": {
                        "gpt_reason": result_json.get("reason"),
                        "chosen_reward": 1.0,
                        "rejected_reward": 0.0 
                    }
                }
    except Exception as e:
        # print(f"Error: {e}")
        pass
    
    return None

def traverse_and_collect_jobs(node, question, history, retriever):
    job = []
    children = node.get('children', [])
    if not children:
        return []

    # 仅收集至少探索过一次的节点
    visited_children = [c for c in children if c.get('n', 0) >= 1]
    
    # 只有当选项 >= 2 时，才值得做对比选择
    if len(visited_children) >= 2:
        candidates = []
        for idx, child in enumerate(visited_children):
            candidates.append({
                "id": idx,
                "action": child.get('action'),
                "q": normalize_mcts_q(child.get('q', 0), child.get('n', 0)),
                "n": child.get('n', 0)
            })
        
        job.append({
            "question": question,
            "history": history,
            "candidates": candidates
        })

    # 递归向下：只走“好路”（n >= 2）
    for child in visited_children:
        if child.get('n', 0) >= 2:
            action_text = child.get('action')
            retrieval_part = perform_retrieval_string(action_text, retriever)
            
            # 保持历史拼接逻辑
            new_history = history + action_text + retrieval_part
            
            subjob = traverse_and_collect_jobs(child, question, new_history, retriever)
            job += subjob
    return job

def main():
    global_client = get_azure_client()
    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)

    print(f"Loading E5 Model ({E5_MODEL_NAME})...")
    similarity_model = SentenceTransformer(E5_MODEL_NAME, device='cuda')

    print(f"Loading Original Data from {ORIGINAL_DATA_PATH}...")
    original_contexts = {}
    try:
        with open(ORIGINAL_DATA_PATH, 'r', encoding='utf-8') as f:
            for line in f:
                try:
                    item = json.loads(line)
                    original_contexts[item['id']] = item['paragraphs']
                except: continue
    except FileNotFoundError:
        print("Skipping context load (file not found). Retrieval will be broken if needed.")

    data = []
    print(f"Parsing Trees from {INPUT_FILE}...")
    with open(INPUT_FILE, 'r', encoding='utf-8') as f:
        for line in tqdm(f, desc="Parsing"):
            line = line.strip()
            if not line: continue
            try:
                tree_obj = json.loads(line)
                idx = tree_obj.get('id')
                q_text = tree_obj.get('question', '')
                root = tree_obj.get('mcts_tree', {})
                
                context_data = original_contexts.get(idx)
                retriever = E5VectorRetriever(context_data, similarity_model) if context_data else None
    
                subdata = traverse_and_collect_jobs(root, q_text, "", retriever)
                data += subdata

            except json.JSONDecodeError:
                continue
    
    print(f"Collected {len(data)} groups of candidates for GPT selection.")
    
    print("Starting GPT-4o Selection...")
    valid_count = 0
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f_out:
        with concurrent.futures.ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
            futures = [executor.submit(process_candidate_group, global_client, item) for item in data]
            
            for future in tqdm(concurrent.futures.as_completed(futures), total=len(data)):
                try:
                    res = future.result()
                    if res:
                        f_out.write(json.dumps(res, ensure_ascii=False) + "\n")
                        f_out.flush()
                        valid_count += 1
                except Exception:
                    pass
    
    print(f"Done. Generated {valid_count} valid pairwise samples.")

if __name__ == "__main__":
    main()